<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="9.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="9.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.JSInterop" Version="9.0.9" />
    <PackageReference Include="Microsoft.VisualStudio.Services.Client" Version="19.225.1" />
	  <PackageReference Include="System.Text.Encoding.CodePages" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BanksDB.Core\BanksDB.Core.csproj" />
    <ProjectReference Include="..\BanksDB.DAL\BanksDB.DAL.csproj" />
  </ItemGroup>

</Project>
